language: erlang
install: true
before_script:
  - wget https://s3.amazonaws.com/rebar3/rebar3
  - chmod +x rebar3
env:
  - PATH=".:$PATH"
script:
  - ./rebar3 as dev compile
  - ./rebar3 as test eunit
otp_release:
  - 20.0
  - 19.1
  - 18.3
  - 17.5
  - R16B03-1